routes/web.php
<?php

Auth::routes();

Route::redirect('/', '/reception/dahsboard')->middleware('auth');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {  
    Route::resource('users', 'UsersController');
    Route::resource('patients', 'PatientController');
});

Route::group(['prefix' => 'reception', 'middleware' => 'auth'], function () {
    Route::view('dahsboard', 'reception.dashboard')->name('reception.dashboard');
});

Route::group(['prefix' => 'medical', 'middleware' => 'auth'], function() {
    Route::view('/agenda', 'medicals.agenda')->name('medicals.agenda');
    Route::view('/serve', 'medicals.serve');
});

Route::group(['prefix' => 'api'], function () {
    Route::resource('consults', 'ConsultController');
    Route::get('medicals', 'MedicalController@index');
    
    Route::post('/patients', 'PatientController@fetech');
    Route::put('/patients/{patient}', 'PatientController@update');
    Route::get('/patients/{patient}/show', 'PatientController@show');
    Route::post('/patients/avatar/{patient}', 'PatientController@avatar');

    Route::post('/users', 'UsersController@store');
    Route::put('/users/{username}', 'UsersController@update');
    Route::post('/users/avatar/{username}', 'UsersController@avatar');
});

app/User.php
<?php

namespace App;

use Clinico\Address\Addressable;
use Clinico\AvatarTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Intervention\Zodiac\EloquentZodiacTrait;

class User extends Authenticatable
{
    use Notifiable, Addressable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 
        'first_name', 
        'last_name', 
        'email',
        'mobil',
        'phone_home',
        'gender',   
        'profile_id',
        'birthday', 
        'password',
        'roles',
        'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected static function boot()
    {
        parent::boot();
        
        static::creating(function ($model) {
            $model->password = bcrypt('secret');
        });
    }

    public function getRouteKeyName()
    {
        return 'username';
    }

    /**
     * Relaciones
     */
    
    public function profile()
    {
        return $this->hasOne(Profile::class)->withDefault();
    }

    public function consults()
    {
        return $this->hasMany(\App\Models\Consult::class, 'created_by');
    }

    public function my_consults()
    {
        return $this->hasMany(\App\Models\Consult::class, 'medical_id');
    }


    public static function insert($data)
    {
        $user = static::create($data);
        //$user->profile()->create($data);
        $user->addresses()->create($data);
        return $user;
    }

    public function updateChange($request)
    {
        $this->update($request);
        $this->addresses()
            ->first()
            ->update($request);
            
        return $this;
    }

    public function getFullNameAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }

    public function scopeMedicals($query)
    {
        return $query->where('roles', 'medical')->get();
    }

    public function isAdmin()
    {
        return (bool) $this->roles == 'admin';
    }

    public function getAvatarPathAttribute()
    {
        return $this->avatar;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserFormRequest;
use App\User;
use Clinico\Avatar;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        return view('users.index')
            ->withUsers(User::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        return view('users.create')->withUser('');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserFormRequest $request)
    {
        $user = User::insert($request->all());
        return response()
            ->json(['data' => $user->fresh()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', [
            'user' => $this->mergeWith($user)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserFormRequest $request, User $username)
    {  
        $username->updateChange($request->all());
        return response()->json(['menssage' => 'Actualizado exitosamente', 'username' => $username->fresh()->username]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $username)
    {
        $user->delete();
        return redirect()->back();
    }

    public function avatar(User $username)
    {
        $avatar = request()->avatar;
        $avatar->storeAs('/public/avatars', $username->username.'.'.$avatar->extension());
        $username->update(['avatar' => $username->username.'.'.$avatar->extension()]);
    }

    protected function mergeWith($model)
    {
        return collect($model)->merge($model->address);
    }
}

resources/views/users/create.blade.php
@extends('layouts.template')

@section('breadcrumb')
	<h3>Usuarios</h3>
	<ol class="breadcrumb breadcrumb-simple">
		<li><a href="/admin">Administrador</a></li>
		<li><a href="/admin/users">Usuarios</a></li>
		<li class="active">Nuevo</li>
	</ol>
@endsection

@section('content')

<form-user :user="{ avatar: null }"></form-user>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.template')

@section('breadcrumb')
	<h3>Editar usuarios</h3>
	<ol class="breadcrumb breadcrumb-simple">
		<li><a href="/admin">Administrador</a></li>
		<li><a href="/admin/users">Usuarios</a></li>
		<li class="active">Editar</li>
	</ol>
@endsection

@section('content')

<form-user :user=" {{ $user }} "></form-user>

@endsection

resources/views/users/index.blade.php
@extends('layouts.template')

@section('breadcrumb')
	<h3>Usuarios</h3>
	<ol class="breadcrumb breadcrumb-simple">
		<li><a href="/admin">Administrador</a></li>
		<li class="active">Usuarios</li>
	</ol>

@endsection

@section('content')


<section class="box-typical">
	<header class="box-typical-header">
		<div class="tbl-row">
			<div class="tbl-cell tbl-cell-title">
				<h3>{{ $users->count() }} Usuarios registrados</h3>
			</div>
			<div class="tbl-cell tbl-cell-actions">
				<a href="/admin/users/create" class="btn btn-success-outline btn-sm">
					<i class="fa fa-user-plus"></i>
					Nuevo
				</a>
			</div>
		</div>
	</header>
	<div class="box-typical-body">
		<div class="table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th></th>
						<th>Nombre</th>
						<th>Cargo</th>
						<th>Email</th>
						<th>Celular</th>
						<th>Accion</th>
					</tr>
				</thead>
				<tbody>
				@foreach($users as $user)
					<tr>
						<td class="table-photo">
							<img src="/storage/avatars/{{ $user->avatar_path }}" alt="" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="{{ $user->full_name }}">
						</td>
						<td>
							<a href="/admin/users/{{ $user->username }}">
								{{ $user->full_name }}
							</a>
						</td>
						<td>{{ __($user->roles) }}</td>
						<td>{{ $user->email }}</td>
						<td>{{ $user->profile->mobil }}</td>
						<td>
							<div class="btn-group">
								<a href="{{ route('users.edit', $user) }}" 
											class="btn btn-info btn-sm">
										<span class="fa fa-edit"></span>
								</a>
								<a href="#" 
											class="btn btn-success btn-sm">
									<span class="fa fa-eye"></span>
								</a>
							</div>
                        </td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>
	</div><!--.box-typical-body-->
</section>

@endsection

resources/views/users/show.blade.php
@extends('layouts.template')

@section('breadcrumb')
	<h3>Usuarios</h3>
	<ol class="breadcrumb breadcrumb-simple">
		<li><a href="/admin">Dashboard</a></li>
		<li><a href="/admin/users">Medicos</a></li>
		<li class="active">{{ $user->full_name }}</li>
	</ol>
@endsection

@section('content')

<div class="row">
	<div class="col-md-3">
		@component('components.card-component')
			@slot('title', $user->full_name." <a href='/admin/users/{$user->username}/edit' class='btn btn-success btn-sm'><i class='fa fa-edit'></i></a>")
			
			@slot('table')
			<img src="/storage/avatars/{{ $user->avatar_path }}" width="100%" alt="">
			@endslot

			@slot('foot')
				<ul class="profile-links-list">
					<li class="nowrap">
						<i class="font-icon font-icon-user"></i>
						Medico
					</li>
					<li class="nowrap">
						<i class="font-icon font-icon-phone"></i>
						{{ $user->profile->mobil }}
					</li>
					<li class="nowrap">
						<i class="font-icon font-icon-mail"></i>
						{{ $user->email }}
					</li>
				</ul>
			@endslot
		@endcomponent

	</div>
	<div class="col-md-9">
	
		@component('components.card-component')
			@slot('title', 'Citas con pacientes')

			@slot('class', 'card-blue')
			
			@slot('table')

				<table class="table table-hover">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Edad</th>
							<th>Sexo</th>
							<th>Fecha de Cita</th>
							<th>Accion</th>
						</tr>
					</thead>
					<tbody>
					@forelse($user->my_consults as $consult)
						<tr>
							<td>{{ $consult->patient->full_name }}</td>
							<td>{{ $consult->patient->age }} año</td>
							<td>{{ $consult->patient->gender }}</td>
							<td>{{ $consult->start }}</td>
							<td>
								<button class="btn btn-success btn-sm">
									Atender
								</button>

								<button class="btn btn-default btn-sm">
									<i class="fa fa-eye"></i>
								</button>
							</td>
						</tr>
					@empty
						<tr>
							<td colspan="6">
								No tiene citas programadas.
							</td>
						</tr>
					@endforelse
					</tbody>
				</table>

			@endslot
		@endcomponent
	</div>
</div>
@endsection